# -*- coding: utf-8 -*-
"""food101_utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ts_x5LywnQtH8E9YC8oXxryisWOI2zY
"""

# !pip -q install streamlit as in streamlit this will throw a error
import torch
from torchvision import transforms
from PIL import Image
import streamlit as st
import os
import json

from food101_model import get_model

device="cpu"
current_dir = os.path.dirname(os.path.abspath(__file__)) if "__file__" in locals() else "."
classes_path = os.path.join(current_dir, "food101_classes.json")

with open(classes_path, "r") as f:
  classes = json.load(f)

#Loading the model
@st.cache_resource
def efficentnetb3_loader():
  url="https://github.com/vikassinngh123/AI-ML-Learning/releases/download/v1.1/final_efficientnet_epoch.pth"
  filename="efficentnetb3_model.pth"
  if not os.path.exists(filename):
    torch.hub.download_url_to_file(url, filename)

  efficentnetb3=get_model(num_classes=101,device=device)

  efficentnetb3.load_state_dict(
                                torch.load("efficentnetb3_model.pth",
                                            map_location=torch.device(device),
                                            weights_only=True
                                           )
                             )
  efficentnetb3.eval()
  return efficentnetb3

#image transformation
def image_transform(uploaded_file):
  transform=transforms.Compose([
                                   transforms.Resize((224,224)),
                                   transforms.ToTensor(),
                                   transforms.Normalize(mean=[0.485,0.456,0.406],std=[0.229,0.224,0.225])
                                   ])
  img = Image.open(uploaded_file).convert('RGB')
  return transform(img)

#prediting the class
def predict(transformed_image,loaded_model):
    batch_img=transformed_image.unsqueeze(0).to(device)
    loaded_model.eval()

    with torch.inference_mode():
        raw_logits=loaded_model(batch_img)
        probs=torch.softmax(raw_logits,dim=1)

        confidence,predicted_index=torch.max(probs, dim=1) #this will give the max value in probs(the values in probs is in b/w 0-1 due to softmax) and also the give the indices the max value is at.
        predicted_class=classes[predicted_index]

        return predicted_class, confidence.item()*100