# -*- coding: utf-8 -*-
"""food101_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195G_Zk_ajJx6RidWkXsberdQiHQz1SOZ
"""

import streamlit as st
import os
from datetime import datetime
from food101_utils import efficentnetb3_loader, image_transform, predict


st.set_page_config(page_title="AI Food Vision", page_icon="🍔", layout="centered")

page_bg_img = """
<style>
[data-testid="stAppViewContainer"] {
    background: linear-gradient(135deg, #1e1e1e 0%, #2b2b2b 100%);
    color: #ffffff; /* Ensures all text is white and readable */
}
[data-testid="stHeader"] {
    background: rgba(0,0,0,0);
}
</style>
"""
st.markdown(page_bg_img, unsafe_allow_html=True)

st.title("Food Classification")
st.markdown("**Upload a photo of your meal, and the EfficientNet-B3 model will identify it!**")

efficentnetb3 = efficentnetb3_loader()


uploaded_file = st.file_uploader(
                                 "Choose an image...",
                                  type=["jpg", "jpeg", "png"]
                                )

if uploaded_file is not None:

  col1, col2 = st.columns(2)

  with col1:
        st.image(uploaded_file, caption="Your Upload", use_container_width=True)

  with col2:
      with st.spinner("Analyzing culinary features..."):
          transformed_img = image_transform(uploaded_file)


          pred_class, confidence = predict(transformed_img, efficentnetb3)

          st.subheader("Prediction:")

          st.success(f"**{pred_class.replace('_', ' ').title()}**")

          st.metric(label="Confidence Score", value=f"{confidence:.2f}%")
          st.progress(int(confidence))

          if confidence > 85.0:
                st.balloons()
