# -*- coding: utf-8 -*-
"""food101_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZ0cuDIeHbwkhbuxsgT-zRB5Mo_7_wdD
"""

import torch
from torch import nn
import torchvision
import torchvision.models as model

def get_model(num_classes=101, device=None):
  efficientnet_model=model.efficientnet_b3(weights='DEFAULT')

  for params in efficientnet_model.features.parameters():
    params.requires_grad=False

  efficientnet_model.classifier=nn.Sequential(
                                              nn.Dropout(p=0.2,inplace=False),

                                              nn.Linear(in_features=1536,out_features=256),
                                              nn.ReLU(),
                                              nn.Dropout(p=0.3,inplace=False),

                                              nn.Linear(in_features=256,out_features=128),
                                              nn.ReLU(),
                                              nn.Dropout(p=0.3,inplace=False),

                                              nn.Linear(in_features=128,out_features=num_classes)
                                              )

  for param in efficientnet_model.features[7].parameters():
    param.requires_grad = True

  for param in efficientnet_model.features[8].parameters():
    param.requires_grad = True

  if device is not None:
        efficientnet_model = efficientnet_model.to(device)

  return efficientnet_model

